name: job-tracker
region: nyc
services:
- name: backend
  source_dir: /backend
  github:
    repo: your-username/job-tracker
    branch: main
  build_command: |
    npm install -g pnpm
    pnpm install --frozen-lockfile
    pnpm db:generate
    pnpm build
  run_command: node dist/server.js
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /api
  envs:
  - key: NODE_ENV
    value: production
  - key: DATABASE_URL
    value: ${job-tracker-db.DATABASE_URL}
  - key: JWT_SECRET
    value: ${JWT_SECRET}
    type: SECRET
  - key: CORS_ORIGIN
    value: https://${APP_DOMAIN}
  - key: PORT
    value: "5000"

- name: frontend
  source_dir: /frontend
  github:
    repo: your-username/job-tracker
    branch: main
  build_command: |
    npm install -g pnpm
    pnpm install --frozen-lockfile
    pnpm build
  run_command: node server.js
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /
  envs:
  - key: NODE_ENV
    value: production
  - key: NEXT_PUBLIC_API_URL
    value: https://${APP_DOMAIN}/api
  - key: NEXTAUTH_SECRET
    value: ${NEXTAUTH_SECRET}
    type: SECRET
  - key: NEXTAUTH_URL
    value: https://${APP_DOMAIN}
  - key: PORT
    value: "3000"
  - key: HOSTNAME
    value: "0.0.0.0"

databases:
- name: job-tracker-db
  engine: PG
  version: "15"
  size: basic-xs
  num_nodes: 1 